### ISSUE TITLE
Type error in documentation

### ISSUE THREAD

**Issue by yechs** [james-bern/eph.h#8]
This is a very minor issue, but I'm posting just in case it also confuses someone else

In the documentation of `transformVector` in hw4,
https://github.com/james-bern/CSCI-371/blob/8bddb7c28bce56da5a3ce3e63c75bacd7aceb6e2/hw.cpp#L100-L102

The return type should be `vec3` instead of `vec2`.

## Analysis

The source code for `transformVector` is located in https://github.com/james-bern/CSCI-371/blob/8bddb7c28bce56da5a3ce3e63c75bacd7aceb6e2/snail.cpp#L404-L411

Since the second input parameter is of type `SnailVec<3>`, the return type should also be `SnailVec<3>`

**Comment by james-bern** [comment]
Thanks Ye! Fixed 🙂💪
